obstacle_range: 2.5          # Max distance to detect obstacles
raytrace_range: 3.0          # Max distance to clear free space
footprint: [[0.55, 0.45], [0.55, -0.45], [-0.55, -0.45], [-0.55, 0.45]]  # Boat footprint
observation_sources: scan    # Use LiDAR data

scan:
  sensor_frame: lidar_center # Matches your URDF's LiDAR frame
  data_type: LaserScan
  topic: /scan              # Matches your gazebo_ros_laser plugin
  marking: true             # Mark obstacles
  clearing: true            # Clear free space
