local_costmap:
  global_frame: odom         # Matches your odom plugin's frameName
  robot_base_frame: baseboatclening  # Matches your URDF base link
  update_frequency: 5.0      # Update at 5 Hz
  publish_frequency: 2.0     # Publish at 2 Hz
  rolling_window: true       # Keep the costmap centered on the boat
  width: 6.0                # 6 m x 6 m local window
  height: 6.0
  resolution: 0.05          # 5 cm grid resolution
